apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: 80
    protocol: TCP
    name: flask
    targetPort: 8000
  selector:
    app: {{ .Values.appName }}
    tier: frontend
  type: NodePort
